// source: rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.lnrpc.InitWalletRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.lnrpc.ChanBackupSnapshot');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lnrpc.InitWalletRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.lnrpc.InitWalletRequest.repeatedFields_, null);
};
goog.inherits(proto.lnrpc.InitWalletRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lnrpc.InitWalletRequest.displayName = 'proto.lnrpc.InitWalletRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.lnrpc.InitWalletRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lnrpc.InitWalletRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.lnrpc.InitWalletRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lnrpc.InitWalletRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lnrpc.InitWalletRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    walletPassword: msg.getWalletPassword_asB64(),
    cipherSeedMnemonicList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    aezeedPassphrase: msg.getAezeedPassphrase_asB64(),
    recoveryWindow: jspb.Message.getFieldWithDefault(msg, 4, 0),
    channelBackups: (f = msg.getChannelBackups()) && proto.lnrpc.ChanBackupSnapshot.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lnrpc.InitWalletRequest}
 */
proto.lnrpc.InitWalletRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lnrpc.InitWalletRequest;
  return proto.lnrpc.InitWalletRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lnrpc.InitWalletRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lnrpc.InitWalletRequest}
 */
proto.lnrpc.InitWalletRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setWalletPassword(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addCipherSeedMnemonic(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAezeedPassphrase(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRecoveryWindow(value);
      break;
    case 5:
      var value = new proto.lnrpc.ChanBackupSnapshot;
      reader.readMessage(value,proto.lnrpc.ChanBackupSnapshot.deserializeBinaryFromReader);
      msg.setChannelBackups(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lnrpc.InitWalletRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lnrpc.InitWalletRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lnrpc.InitWalletRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lnrpc.InitWalletRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWalletPassword_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getCipherSeedMnemonicList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getAezeedPassphrase_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getRecoveryWindow();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getChannelBackups();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.lnrpc.ChanBackupSnapshot.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes wallet_password = 1;
 * @return {string}
 */
proto.lnrpc.InitWalletRequest.prototype.getWalletPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes wallet_password = 1;
 * This is a type-conversion wrapper around `getWalletPassword()`
 * @return {string}
 */
proto.lnrpc.InitWalletRequest.prototype.getWalletPassword_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getWalletPassword()));
};


/**
 * optional bytes wallet_password = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getWalletPassword()`
 * @return {!Uint8Array}
 */
proto.lnrpc.InitWalletRequest.prototype.getWalletPassword_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getWalletPassword()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.lnrpc.InitWalletRequest} returns this
 */
proto.lnrpc.InitWalletRequest.prototype.setWalletPassword = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * repeated string cipher_seed_mnemonic = 2;
 * @return {!Array<string>}
 */
proto.lnrpc.InitWalletRequest.prototype.getCipherSeedMnemonicList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.lnrpc.InitWalletRequest} returns this
 */
proto.lnrpc.InitWalletRequest.prototype.setCipherSeedMnemonicList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.lnrpc.InitWalletRequest} returns this
 */
proto.lnrpc.InitWalletRequest.prototype.addCipherSeedMnemonic = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.lnrpc.InitWalletRequest} returns this
 */
proto.lnrpc.InitWalletRequest.prototype.clearCipherSeedMnemonicList = function() {
  return this.setCipherSeedMnemonicList([]);
};


/**
 * optional bytes aezeed_passphrase = 3;
 * @return {string}
 */
proto.lnrpc.InitWalletRequest.prototype.getAezeedPassphrase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes aezeed_passphrase = 3;
 * This is a type-conversion wrapper around `getAezeedPassphrase()`
 * @return {string}
 */
proto.lnrpc.InitWalletRequest.prototype.getAezeedPassphrase_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAezeedPassphrase()));
};


/**
 * optional bytes aezeed_passphrase = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAezeedPassphrase()`
 * @return {!Uint8Array}
 */
proto.lnrpc.InitWalletRequest.prototype.getAezeedPassphrase_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAezeedPassphrase()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.lnrpc.InitWalletRequest} returns this
 */
proto.lnrpc.InitWalletRequest.prototype.setAezeedPassphrase = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional int32 recovery_window = 4;
 * @return {number}
 */
proto.lnrpc.InitWalletRequest.prototype.getRecoveryWindow = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.lnrpc.InitWalletRequest} returns this
 */
proto.lnrpc.InitWalletRequest.prototype.setRecoveryWindow = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional ChanBackupSnapshot channel_backups = 5;
 * @return {?proto.lnrpc.ChanBackupSnapshot}
 */
proto.lnrpc.InitWalletRequest.prototype.getChannelBackups = function() {
  return /** @type{?proto.lnrpc.ChanBackupSnapshot} */ (
    jspb.Message.getWrapperField(this, proto.lnrpc.ChanBackupSnapshot, 5));
};


/**
 * @param {?proto.lnrpc.ChanBackupSnapshot|undefined} value
 * @return {!proto.lnrpc.InitWalletRequest} returns this
*/
proto.lnrpc.InitWalletRequest.prototype.setChannelBackups = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lnrpc.InitWalletRequest} returns this
 */
proto.lnrpc.InitWalletRequest.prototype.clearChannelBackups = function() {
  return this.setChannelBackups(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lnrpc.InitWalletRequest.prototype.hasChannelBackups = function() {
  return jspb.Message.getField(this, 5) != null;
};


